### ISSUE TITLE
Обожаю аркад бравл ❤️❤️

### ISSUE THREAD

**Issue by shark01d** [bkvdn2/AutismBrawl#2]
⚠️ ОФИЦИАЛЬНОЕ СООБЩЕНИЕ ОТ SRENDLEZZ TEAM ⚠️
🇨🇿 МЫ ОФИЦИАЛЬНО ЗАЯВЛЯЕМ, ЧТО НА НАШЕМ СЕРВЕРЕ МОЖНО БУДЕТ ИГРАТЬ ТОЛЬКО ГЕЯМ 🇨🇿
😨 ДЛЯ ВХОДА В ИГРУ НУЖНО БУДЕТ ПРОЙТИ ПРОВЕРКУ 😨
✅ ГЕИ, НЕ БОЙТЕСЬ, НАТУРАЛОВ НЕ ВПУСТЯТ ✅

**Comment by bkvdn2** [comment]
объединение AutismBrawl и SrendleZZZ Team??

**Comment by shark01d** [comment]
- Я АУТИЗМ ВОЕННЫЙ БРАВЛ ПРЕДЛАГАЮ СЛОЖИТЬ ОРУЖИЕ И СДАТЬСЯ
- АУТИЗМ ВОЕННЫЙ БРАВЛ ИДИ НАХ*Й

**Comment by bkvdn2** [comment]
шл@кдев

**Comment by shark01d** [comment]
сраня лох
